#!/usr/bin/env python3
"""
report_generator.py — Structured report builder for scan findings.

Outputs JSON (for programmatic consumption) or Markdown (for human review).
Includes scan metadata, scope authorization, and prioritized findings.

Author: Vincent Phan
"""

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


@dataclass
class ReportGenerator:
    """Generate a structured report from scored findings."""

    scope: str
    scan_meta: Any  # ScanMetadata dataclass from nmap_parser
    findings: List[Dict[str, Any]]
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_json(self) -> str:
        """Return a JSON string with full structured report."""
        report = {
            "report_version": "1.0.0",
            "generated_at": self.generated_at,
            "scope_authorization": self.scope,
            "scan_metadata": self._meta_to_dict(),
            "summary": self._build_summary(),
            "findings": self.findings,
        }
        return json.dumps(report, indent=2)

    def to_markdown(self) -> str:
        """Return a Markdown string suitable for SOC triage or handoff."""
        lines = [
            "# Network Reconnaissance Report",
            "",
            f"**Generated:** {self.generated_at}",
            f"**Scope Authorization:** {self.scope}",
            "",
            "## Scan Metadata",
            "",
            f"- **Scanner:** {self.scan_meta.scanner}",
            f"- **nmap Version:** {self.scan_meta.nmap_version or 'unknown'}",
            f"- **Command Args:** `{self.scan_meta.args}`",
            f"- **Start Time:** {self.scan_meta.start_time or 'unknown'}",
            "",
            "## Summary",
            "",
            self._summary_table(),
            "",
            "## Findings (Prioritized by Risk)",
            "",
        ]

        for idx, finding in enumerate(self.findings, 1):
            lines.extend(self._finding_section(finding, idx))

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "*This report was generated by an automated reconnaissance wrapper. "
            "All findings should be verified by a human analyst before action.*"
        )

        return "\n".join(lines)

    def _meta_to_dict(self) -> Dict[str, Any]:
        """Convert ScanMetadata to a plain dict."""
        return {
            "scanner": self.scan_meta.scanner,
            "args": self.scan_meta.args,
            "start_time": self.scan_meta.start_time,
            "nmap_version": self.scan_meta.nmap_version,
            "xml_version": self.scan_meta.xml_version,
        }

    def _build_summary(self) -> Dict[str, Any]:
        """Build a rollup summary of findings by severity."""
        counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        for f in self.findings:
            sev = f.get("severity", "info")
            counts[sev] = counts.get(sev, 0) + 1

        total = sum(counts.values())
        return {
            "total_findings": total,
            "severity_counts": counts,
            "hosts_scanned": len({f["host_ip"] for f in self.findings}),
        }

    def _summary_table(self) -> str:
        """Build a Markdown table for the summary section."""
        summary = self._build_summary()
        lines = [
            "| Severity | Count |",
            "|----------|-------|",
            f"| Critical | {summary['severity_counts'].get('critical', 0)} |",
            f"| High     | {summary['severity_counts'].get('high', 0)} |",
            f"| Medium   | {summary['severity_counts'].get('medium', 0)} |",
            f"| Low      | {summary['severity_counts'].get('low', 0)} |",
            f"| **Total** | **{summary['total_findings']}** |",
        ]
        return "\n".join(lines)

    def _finding_section(self, finding: Dict[str, Any], idx: int) -> List[str]:
        """Build a Markdown section for a single finding."""
        sev = finding.get("severity", "info").upper()
        score = finding.get("risk_score", 0)
        lines = [
            f"### {idx}. [{sev}] {finding.get('service_name', 'unknown')} on {finding['host_ip']}:{finding['port']}",
            "",
            f"- **Risk Score:** {score}/100",
            f"- **Host:** {finding['host_ip']} ({finding.get('host_hostname', 'n/a')})",
            f"- **Port:** {finding['port']}/{finding.get('protocol', 'tcp')}",
            f"- **Service:** {finding.get('service_name', 'unknown')} {finding.get('service_version', '')}",
            f"- **Banner:** `{finding.get('banner', 'n/a')}`",
            f"- **OS Guess:** {finding.get('host_os', 'n/a')}",
        ]

        cves = finding.get("cves", [])
        if cves:
            lines.append(f"- **Known CVEs:** {', '.join(cves)}")
        else:
            lines.append("- **Known CVEs:** None in curated database")

        lines.append(f"- **Remediation:** {finding.get('remediation', 'Review and patch.')}")
        lines.append("")
        return lines
